In [ ]:
# Cell 1 — Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Cell 2 — Install (restart kernel after this cell)
import subprocess
subprocess.run(['pip', 'install', '-q',
    'transformers==4.46.3',
    'datasets',
    'seqeval',
    'accelerate',
])
print('Done. Restart kernel now, then run all cells below.')

Done. Restart kernel now, then run all cells below.

In [ ]:
# Cell 3 — Imports
import os
import gc
import random
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm
from datasets import load_dataset, Dataset as HFDataset, concatenate_datasets
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForTokenClassification,
)
from seqeval.metrics import f1_score, classification_report

random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

print('Imports OK')
print(f'PyTorch: {torch.__version__}')
print(f'CUDA: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'Free: {torch.cuda.mem_get_info()[0]/1e9:.1f} GB')

Imports OK
PyTorch: 2.10.0+cu128
CUDA: True
GPU: Tesla T4
Free: 15.5 GB

In [ ]:
# Cell 4 — Label maps
LABEL_LIST = ['O', 'B-SKILL', 'I-SKILL']
LABEL2ID   = {l: i for i, l in enumerate(LABEL_LIST)}
ID2LABEL   = {i: l for i, l in enumerate(LABEL_LIST)}
print('Labels:', LABEL2ID)

Labels: {'O': 0, 'B-SKILL': 1, 'I-SKILL': 2}

In [ ]:
# Cell 5 — Tag normalisation (merges tags_skill + tags_knowledge)
def normalise_tag(tag):
    if tag in ('B', 'B-SOFT', 'B-ICT', 'B-SKILL',
               'B-PENSEE', 'B-RESULTATS', 'B-RELATIONNEL', 'B-PERSONNEL'):
        return 'B-SKILL'
    if tag in ('I', 'I-SOFT', 'I-ICT', 'I-SKILL',
               'I-PENSEE', 'I-RESULTATS', 'I-RELATIONNEL', 'I-PERSONNEL'):
        return 'I-SKILL'
    return 'O'

def get_tokens_and_tags(example):
    """Merges tags_skill + tags_knowledge (where present) into B-SKILL/I-SKILL/O."""
    tokens = example['tokens']
    merged = ['O'] * len(tokens)
    for col in ('tags_skill', 'tags_knowledge'):
        if col not in example:
            continue
        for i, tag in enumerate(example[col]):
            norm = normalise_tag(str(tag))
            if norm != 'O' and merged[i] == 'O':
                merged[i] = norm
    return tokens, merged

print('Tag normalisation defined')

Tag normalisation defined

In [ ]:
# Cell 6 — Load all 4 English datasets + combine into single train/test split
say = load_dataset('jjzha/sayfullina')
skl = load_dataset('jjzha/skillspan')
grn = load_dataset('jjzha/green')
gnh = load_dataset('jjzha/gnehm')

ALL_DATASETS = [
    ('sayfullina', say),
    ('skillspan',  skl),
    ('green',      grn),
    ('gnehm',      gnh),
]

print('Individual dataset sizes:')
for name, ds in ALL_DATASETS:
    skill_count = sum(
        1 for ex in ds['train']
        if any(t != 'O' for t in get_tokens_and_tags(ex)[1])
    )
    print(f'  {name:12} train={len(ds["train"]):5}  test={len(ds["test"]):4}  with_skills={skill_count}')

print(f'\nTotal train: {sum(len(ds["train"]) for _, ds in ALL_DATASETS)}')
print(f'Total test:  {sum(len(ds["test"])  for _, ds in ALL_DATASETS)}')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

train.json: 0.00B [00:00, ?B/s]

dev.json: 0.00B [00:00, ?B/s]

test.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/3705 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1855 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1851 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

train.json: 0.00B [00:00, ?B/s]

dev.json: 0.00B [00:00, ?B/s]

test.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/4800 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3174 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3569 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

train.json: 0.00B [00:00, ?B/s]

dev.json: 0.00B [00:00, ?B/s]

test.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/8669 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/964 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/335 [00:00<?, ? examples/s]

README.md: 0.00B [00:00, ?B/s]

train.json: 0.00B [00:00, ?B/s]

dev.json: 0.00B [00:00, ?B/s]

test.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/19889 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2332 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2557 [00:00<?, ? examples/s]

Individual dataset sizes:
  sayfullina   train= 3705  test=1851  with_skills=3701
  skillspan    train= 4800  test=3569  with_skills=1584
  green        train= 8669  test= 335  with_skills=5136
  gnehm        train=19889  test=2557  with_skills=3408

Total train: 37063
Total test:  8312

In [ ]:
# Cell 7 — Tokenise + align labels
def tokenize_and_align(examples, tokenizer, max_length=128):
    tokenized = tokenizer(
        examples['tokens'],
        truncation=True,
        max_length=max_length,
        is_split_into_words=True,
    )
    all_labels = []
    for i in range(len(examples['tokens'])):
        word_ids  = tokenized.word_ids(batch_index=i)
        tags      = examples['ner_tags'][i]
        label_ids = []
        prev_word = None
        for word_id in word_ids:
            if word_id is None:
                label_ids.append(-100)
            elif word_id != prev_word:
                label_ids.append(LABEL2ID[tags[word_id]])
            else:
                label_ids.append(-100)
            prev_word = word_id
        all_labels.append(label_ids)
    tokenized['labels'] = all_labels
    return tokenized

def build_hf_split(ds_split, tokenizer, desc=''):
    records = []
    for ex in tqdm(ds_split, desc=desc):
        tokens, tags = get_tokens_and_tags(ex)
        records.append({'tokens': tokens, 'ner_tags': tags})
    hf = HFDataset.from_list(records)
    hf = hf.map(
        lambda batch: tokenize_and_align(batch, tokenizer),
        batched=True,
        remove_columns=['tokens', 'ner_tags'],
    )
    return hf

print('Tokenisation defined')

Tokenisation defined

In [ ]:
# Cell 8 — Compute metrics (seqeval strict F1)
def make_compute_metrics():
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        true_labels = [
            [ID2LABEL[l] for l in label_row if l != -100]
            for label_row in labels
        ]
        true_preds = [
            [ID2LABEL[p] for p, l in zip(pred_row, label_row) if l != -100]
            for pred_row, label_row in zip(predictions, labels)
        ]
        return {'f1': f1_score(true_labels, true_preds)}
    return compute_metrics

print('Metrics defined')

Metrics defined

In [ ]:
# Cell 9 — Models to train (one combined model per architecture)
MODELS = {
    'bert-base':    'bert-base-cased',
    'spanbert':     'SpanBERT/spanbert-base-cased',
    'jobbert':      'jjzha/jobbert-base-cased',
    'jobspanbert':  'jjzha/jobspanbert-base-cased',
}
print('Models to train:')
for k, v in MODELS.items():
    print(f'  {k:14} → {v}')

Models to train:
  bert-base      → bert-base-cased
  spanbert       → SpanBERT/spanbert-base-cased
  jobbert        → jjzha/jobbert-base-cased
  jobspanbert    → jjzha/jobspanbert-base-cased

In [ ]:
# Cell 10 — Training loop: one combined model per architecture
# Trains on all 4 datasets concatenated → single model per architecture
# Saves to Google Drive

RESULTS = {}  # model_name → {overall_f1, per_dataset_f1}

for model_name, model_id in MODELS.items():
    print(f'\n{"="*60}')
    print(f'MODEL: {model_name} ({model_id})')
    print(f'{"="*60}')

    tokenizer = AutoTokenizer.from_pretrained(model_id)

    # Build combined train split from all 4 datasets
    print('Building combined training set...')
    all_train_records = []
    for name, ds in ALL_DATASETS:
        for ex in tqdm(ds['train'], desc=f'  {name}'):
            tokens, tags = get_tokens_and_tags(ex)
            all_train_records.append({'tokens': tokens, 'ner_tags': tags})

    # Shuffle combined training set
    random.shuffle(all_train_records)
    combined_train_hf = HFDataset.from_list(all_train_records)
    combined_train_hf = combined_train_hf.map(
        lambda batch: tokenize_and_align(batch, tokenizer),
        batched=True,
        remove_columns=['tokens', 'ner_tags'],
    )
    print(f'Combined train size: {len(combined_train_hf)}')

    # Build combined test split
    print('Building combined test set...')
    all_test_records = []
    for name, ds in ALL_DATASETS:
        for ex in tqdm(ds['test'], desc=f'  {name}'):
            tokens, tags = get_tokens_and_tags(ex)
            all_test_records.append({'tokens': tokens, 'ner_tags': tags})

    combined_test_hf = HFDataset.from_list(all_test_records)
    combined_test_hf = combined_test_hf.map(
        lambda batch: tokenize_and_align(batch, tokenizer),
        batched=True,
        remove_columns=['tokens', 'ner_tags'],
    )
    print(f'Combined test size:  {len(combined_test_hf)}')

    model = AutoModelForTokenClassification.from_pretrained(
        model_id,
        num_labels=len(LABEL_LIST),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
        ignore_mismatched_sizes=True,
    )

    save_dir = f'/content/drive/MyDrive/phaseA_combined/{model_name}'
    os.makedirs(save_dir, exist_ok=True)

    training_args = TrainingArguments(
        output_dir                  = save_dir,
        num_train_epochs            = 3,
        per_device_train_batch_size = 16,
        per_device_eval_batch_size  = 32,
        learning_rate               = 2e-5,
        weight_decay                = 0.01,
        warmup_ratio                = 0.1,
        evaluation_strategy         = 'epoch',
        save_strategy               = 'epoch',
        load_best_model_at_end      = True,
        metric_for_best_model       = 'eval_f1',
        fp16                        = True,
        logging_steps               = 50,
        report_to                   = 'none',
        seed                        = 42,
    )

    trainer = Trainer(
        model           = model,
        args            = training_args,
        train_dataset   = combined_train_hf,
        eval_dataset    = combined_test_hf,
        tokenizer       = tokenizer,
        data_collator   = DataCollatorForTokenClassification(tokenizer),
        compute_metrics = make_compute_metrics(),
    )

    trainer.train()

    metrics = trainer.evaluate()
    overall_f1 = metrics['eval_f1']
    print(f'\n{model_name} combined F1: {overall_f1:.4f}')

    trainer.save_model(save_dir + '/best')
    tokenizer.save_pretrained(save_dir + '/best')
    print(f'Saved to {save_dir}/best')

    RESULTS[model_name] = overall_f1

    del model, trainer, combined_train_hf, combined_test_hf
    gc.collect()
    torch.cuda.empty_cache()

print('\nAll models trained.')

============================================================
MODEL: bert-base (bert-base-cased)
============================================================

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Building combined training set...

  sayfullina: 100%|██████████| 3705/3705 [00:01<00:00, 2310.47it/s]
  skillspan: 100%|██████████| 4800/4800 [00:03<00:00, 1422.79it/s]
  green: 100%|██████████| 8669/8669 [00:03<00:00, 2495.73it/s]
  gnehm: 100%|██████████| 19889/19889 [00:01<00:00, 14127.08it/s]

Map:   0%|          | 0/37063 [00:00<?, ? examples/s]

Combined train size: 37063
Building combined test set...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 7019.31it/s]
  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 5768.19it/s]
  green: 100%|██████████| 335/335 [00:00<00:00, 4585.67it/s]
  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 8332.03it/s]

Map:   0%|          | 0/8312 [00:00<?, ? examples/s]

Combined test size:  8312

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_1528/299690349.py:77: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

bert-base combined F1: 0.6547
Saved to /content/drive/MyDrive/phaseA_combined/bert-base/best

============================================================
MODEL: spanbert (SpanBERT/spanbert-base-cased)
============================================================

config.json:   0%|          | 0.00/413 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Building combined training set...

  sayfullina: 100%|██████████| 3705/3705 [00:00<00:00, 5458.90it/s]
  skillspan: 100%|██████████| 4800/4800 [00:01<00:00, 3995.68it/s]
  green: 100%|██████████| 8669/8669 [00:02<00:00, 3051.70it/s]
  gnehm: 100%|██████████| 19889/19889 [00:02<00:00, 8727.93it/s]

Map:   0%|          | 0/37063 [00:00<?, ? examples/s]

Combined train size: 37063
Building combined test set...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 12539.70it/s]
  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 8207.68it/s]
  green: 100%|██████████| 335/335 [00:00<00:00, 6979.05it/s]
  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 13066.65it/s]

Map:   0%|          | 0/8312 [00:00<?, ? examples/s]

Combined test size:  8312

pytorch_model.bin:   0%|          | 0.00/215M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at SpanBERT/spanbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_1528/299690349.py:77: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

model.safetensors:   0%|          | 0.00/215M [00:00<?, ?B/s]

spanbert combined F1: 0.6266
Saved to /content/drive/MyDrive/phaseA_combined/spanbert/best

============================================================
MODEL: jobbert (jjzha/jobbert-base-cased)
============================================================

tokenizer_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/603 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Building combined training set...

  sayfullina: 100%|██████████| 3705/3705 [00:00<00:00, 8672.90it/s]
  skillspan: 100%|██████████| 4800/4800 [00:00<00:00, 5075.89it/s]
  green: 100%|██████████| 8669/8669 [00:01<00:00, 6767.88it/s]
  gnehm: 100%|██████████| 19889/19889 [00:02<00:00, 8771.11it/s]

Map:   0%|          | 0/37063 [00:00<?, ? examples/s]

Combined train size: 37063
Building combined test set...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 4208.29it/s]
  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 4486.02it/s]
  green: 100%|██████████| 335/335 [00:00<00:00, 2991.24it/s]
  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 9882.63it/s]

Map:   0%|          | 0/8312 [00:00<?, ? examples/s]

Combined test size:  8312

model.safetensors:   0%|          | 0.00/433M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at jjzha/jobbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_1528/299690349.py:77: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

jobbert combined F1: 0.6575
Saved to /content/drive/MyDrive/phaseA_combined/jobbert/best

============================================================
MODEL: jobspanbert (jjzha/jobspanbert-base-cased)
============================================================

tokenizer_config.json:   0%|          | 0.00/320 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/337 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Building combined training set...

  sayfullina: 100%|██████████| 3705/3705 [00:00<00:00, 9348.84it/s]
  skillspan: 100%|██████████| 4800/4800 [00:00<00:00, 5533.30it/s]
  green: 100%|██████████| 8669/8669 [00:02<00:00, 4167.46it/s]
  gnehm: 100%|██████████| 19889/19889 [00:03<00:00, 5180.83it/s]

Map:   0%|          | 0/37063 [00:00<?, ? examples/s]

Combined train size: 37063
Building combined test set...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 7570.32it/s]
  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 5998.67it/s]
  green: 100%|██████████| 335/335 [00:00<00:00, 4671.79it/s]
  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 9331.51it/s]

Map:   0%|          | 0/8312 [00:00<?, ? examples/s]

Combined test size:  8312

model.safetensors:   0%|          | 0.00/539M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at jjzha/jobspanbert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_1528/299690349.py:77: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

jobspanbert combined F1: 0.6537
Saved to /content/drive/MyDrive/phaseA_combined/jobspanbert/best

All models trained.

In [ ]:
# Cell 11 — Per-dataset F1 breakdown for each saved model
# Loads each saved model and evaluates on each dataset's test split separately

per_dataset_results = {}  # (model_name, ds_name) → f1

for model_name in MODELS:
    model_path = f'/content/drive/MyDrive/phaseA_combined/{model_name}/best'
    print(f'\nEvaluating {model_name}...')

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForTokenClassification.from_pretrained(model_path)
    model.eval()

    for ds_name, ds in ALL_DATASETS:
        test_hf = build_hf_split(ds['test'], tokenizer, desc=f'  {ds_name}')

        eval_args = TrainingArguments(
            output_dir='/tmp/eval',
            per_device_eval_batch_size=32,
            report_to='none',
            fp16=torch.cuda.is_available(),
        )
        evaluator = Trainer(
            model           = model,
            args            = eval_args,
            eval_dataset    = test_hf,
            tokenizer       = tokenizer,
            data_collator   = DataCollatorForTokenClassification(tokenizer),
            compute_metrics = make_compute_metrics(),
        )
        metrics = evaluator.evaluate()
        f1 = metrics['eval_f1']
        per_dataset_results[(model_name, ds_name)] = f1
        print(f'  {ds_name:12} F1 = {f1:.4f}')

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()

Evaluating bert-base...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 8026.23it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina   F1 = 0.8278

  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 3904.79it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan    F1 = 0.5014

  green: 100%|██████████| 335/335 [00:00<00:00, 4218.89it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green        F1 = 0.4459

  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 8569.93it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm        F1 = 0.8260

Evaluating spanbert...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 14117.79it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina   F1 = 0.8003

  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 9387.33it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan    F1 = 0.4765

  green: 100%|██████████| 335/335 [00:00<00:00, 4255.28it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green        F1 = 0.3983

  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 8398.27it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm        F1 = 0.7913

Evaluating jobbert...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 13359.82it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina   F1 = 0.8091

  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 9347.28it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan    F1 = 0.5429

  green: 100%|██████████| 335/335 [00:00<00:00, 3932.64it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green        F1 = 0.4079

  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 15249.56it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm        F1 = 0.8070

Evaluating jobspanbert...

  sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 13213.97it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina   F1 = 0.8207

  skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 9962.41it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan    F1 = 0.5329

  green: 100%|██████████| 335/335 [00:00<00:00, 3641.01it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green        F1 = 0.4085

  gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 14577.91it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/4129834275.py:23: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm        F1 = 0.7828

In [ ]:
# Cell 12 — Results summary table + save to Drive
ds_names    = [n for n, _ in ALL_DATASETS]
model_names = list(MODELS.keys())

print(f'{"Model":<15}', end='')
for ds in ds_names:
    print(f'{ds:>12}', end='')
print(f'{"Avg":>8}')
print('-' * (15 + 12 * len(ds_names) + 8))

for model_name in model_names:
    f1s = [per_dataset_results.get((model_name, ds), 0.0) for ds in ds_names]
    avg = sum(f1s) / len(f1s)
    print(f'{model_name:<15}', end='')
    for f1 in f1s:
        print(f'{f1:>12.4f}', end='')
    print(f'{avg:>8.4f}')

# Save to Drive
rows = []
for (model_name, ds_name), f1 in per_dataset_results.items():
    rows.append({'model': model_name, 'dataset': ds_name, 'f1': f1})
df = pd.DataFrame(rows)
os.makedirs('/content/drive/MyDrive/phaseA_combined', exist_ok=True)
df.to_csv('/content/drive/MyDrive/phaseA_combined/results.csv', index=False)
print('\nSaved results.csv to Drive')

Model            sayfullina   skillspan       green       gnehm     Avg
-----------------------------------------------------------------------
bert-base            0.8278      0.5014      0.4459      0.8260  0.6503
spanbert             0.8003      0.4765      0.3983      0.7913  0.6166
jobbert              0.8091      0.5429      0.4079      0.8070  0.6417
jobspanbert          0.8207      0.5329      0.4085      0.7828  0.6362

Saved results.csv to Drive

In [ ]:
# Cell 12 — Per-dataset precision, recall, F1 + save token-level predictions to Drive

from seqeval.metrics import precision_score, recall_score, f1_score, classification_report
import numpy as np
import pandas as pd
import os

def get_predictions(model, tokenizer, hf_dataset):
    """Run inference on a tokenised HF dataset, return true + pred label sequences."""
    eval_args = TrainingArguments(
        output_dir='/tmp/eval',
        per_device_eval_batch_size=32,
        report_to='none',
        fp16=torch.cuda.is_available(),
    )
    evaluator = Trainer(
        model           = model,
        args            = eval_args,
        eval_dataset    = hf_dataset,
        tokenizer       = tokenizer,
        data_collator   = DataCollatorForTokenClassification(tokenizer),
        compute_metrics = make_compute_metrics(),
    )
    output = evaluator.predict(hf_dataset)
    logits, labels = output.predictions, output.label_ids
    predictions = np.argmax(logits, axis=-1)

    true_seqs = [
        [ID2LABEL[l] for l in label_row if l != -100]
        for label_row in labels
    ]
    pred_seqs = [
        [ID2LABEL[p] for p, l in zip(pred_row, label_row) if l != -100]
        for pred_row, label_row in zip(predictions, labels)
    ]
    return true_seqs, pred_seqs


all_rows = []           # token-level rows for CSV
summary_rows = []       # per-model per-dataset P/R/F1

for model_name in MODELS:
    model_path = f'/content/drive/MyDrive/phaseA_combined/{model_name}/best'
    print(f'\n{"="*55}')
    print(f'Model: {model_name}')
    print(f'{"="*55}')

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model     = AutoModelForTokenClassification.from_pretrained(model_path)
    model.eval()

    for ds_name, ds in ALL_DATASETS:
        # Build per-dataset test split (keep raw tokens for CSV)
        raw_records = []
        for ex in tqdm(ds['test'], desc=f'  Preparing {ds_name}'):
            tokens, tags = get_tokens_and_tags(ex)
            raw_records.append({'tokens': tokens, 'ner_tags': tags})

        test_hf = HFDataset.from_list(raw_records)
        test_hf_tok = test_hf.map(
            lambda batch: tokenize_and_align(batch, tokenizer),
            batched=True,
            remove_columns=['tokens', 'ner_tags'],
        )

        true_seqs, pred_seqs = get_predictions(model, tokenizer, test_hf_tok)

        p  = precision_score(true_seqs, pred_seqs)
        r  = recall_score(true_seqs, pred_seqs)
        f1 = f1_score(true_seqs, pred_seqs)

        print(f'\n  {ds_name}')
        print(f'    Precision: {p:.4f}')
        print(f'    Recall:    {r:.4f}')
        print(f'    F1:        {f1:.4f}')
        print(classification_report(true_seqs, pred_seqs))

        summary_rows.append({
            'model':     model_name,
            'dataset':   ds_name,
            'precision': round(p,  4),
            'recall':    round(r,  4),
            'f1':        round(f1, 4),
        })

        # Token-level rows
        example_id = 0
        for raw, true_seq, pred_seq in zip(raw_records, true_seqs, pred_seqs):
            tokens = raw['tokens']
            for token_id, (token, gold, pred) in enumerate(zip(tokens, true_seq, pred_seq)):
                all_rows.append({
                    'model':      model_name,
                    'dataset':    ds_name,
                    'example_id': example_id,
                    'token_id':   token_id,
                    'token':      token,
                    'gold':       gold,
                    'pred':       pred,
                })
            example_id += 1

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()

# Save summary P/R/F1
summary_df = pd.DataFrame(summary_rows)
print('\n\n=== SUMMARY ===')
print(summary_df.to_string(index=False))
os.makedirs('/content/drive/MyDrive/phaseA_combined', exist_ok=True)
summary_df.to_csv('/content/drive/MyDrive/phaseA_combined/results_prf.csv', index=False)
print('\nSaved results_prf.csv')

# Save token-level predictions
tokens_df = pd.DataFrame(all_rows)
tokens_df.to_csv('/content/drive/MyDrive/phaseA_combined/predictions_tokens.csv', index=False)
print(f'Saved predictions_tokens.csv  ({len(tokens_df)} rows)')
tokens_df.head(20)

=======================================================
Model: bert-base
=======================================================

  Preparing sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 2684.76it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina
    Precision: 0.8007
    Recall:    0.8568
    F1:        0.8278
              precision    recall  f1-score   support

       SKILL       0.80      0.86      0.83      1857

   micro avg       0.80      0.86      0.83      1857
   macro avg       0.80      0.86      0.83      1857
weighted avg       0.80      0.86      0.83      1857

  Preparing skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 4764.46it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan
    Precision: 0.4894
    Recall:    0.5141
    F1:        0.5014
              precision    recall  f1-score   support

       SKILL       0.49      0.51      0.50      2235

   micro avg       0.49      0.51      0.50      2235
   macro avg       0.49      0.51      0.50      2235
weighted avg       0.49      0.51      0.50      2235

  Preparing green: 100%|██████████| 335/335 [00:00<00:00, 7819.45it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green
    Precision: 0.4991
    Recall:    0.4030
    F1:        0.4459
              precision    recall  f1-score   support

       SKILL       0.50      0.40      0.45       670

   micro avg       0.50      0.40      0.45       670
   macro avg       0.50      0.40      0.45       670
weighted avg       0.50      0.40      0.45       670

  Preparing gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 9951.03it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm
    Precision: 0.8164
    Recall:    0.8359
    F1:        0.8260
              precision    recall  f1-score   support

       SKILL       0.82      0.84      0.83       835

   micro avg       0.82      0.84      0.83       835
   macro avg       0.82      0.84      0.83       835
weighted avg       0.82      0.84      0.83       835


=======================================================
Model: spanbert
=======================================================

  Preparing sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 12322.29it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina
    Precision: 0.7795
    Recall:    0.8223
    F1:        0.8003
              precision    recall  f1-score   support

       SKILL       0.78      0.82      0.80      1857

   micro avg       0.78      0.82      0.80      1857
   macro avg       0.78      0.82      0.80      1857
weighted avg       0.78      0.82      0.80      1857

  Preparing skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 8778.99it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan
    Precision: 0.4761
    Recall:    0.4770
    F1:        0.4765
              precision    recall  f1-score   support

       SKILL       0.48      0.48      0.48      2235

   micro avg       0.48      0.48      0.48      2235
   macro avg       0.48      0.48      0.48      2235
weighted avg       0.48      0.48      0.48      2235

  Preparing green: 100%|██████████| 335/335 [00:00<00:00, 7552.43it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green
    Precision: 0.4566
    Recall:    0.3532
    F1:        0.3983
              precision    recall  f1-score   support

       SKILL       0.46      0.35      0.40       671

   micro avg       0.46      0.35      0.40       671
   macro avg       0.46      0.35      0.40       671
weighted avg       0.46      0.35      0.40       671

  Preparing gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 8180.29it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm
    Precision: 0.7816
    Recall:    0.8012
    F1:        0.7913
              precision    recall  f1-score   support

       SKILL       0.78      0.80      0.79       840

   micro avg       0.78      0.80      0.79       840
   macro avg       0.78      0.80      0.79       840
weighted avg       0.78      0.80      0.79       840


=======================================================
Model: jobbert
=======================================================

  Preparing sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 13003.01it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina
    Precision: 0.7836
    Recall:    0.8363
    F1:        0.8091
              precision    recall  f1-score   support

       SKILL       0.78      0.84      0.81      1857

   micro avg       0.78      0.84      0.81      1857
   macro avg       0.78      0.84      0.81      1857
weighted avg       0.78      0.84      0.81      1857

  Preparing skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 8733.33it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan
    Precision: 0.5194
    Recall:    0.5687
    F1:        0.5429
              precision    recall  f1-score   support

       SKILL       0.52      0.57      0.54      2235

   micro avg       0.52      0.57      0.54      2235
   macro avg       0.52      0.57      0.54      2235
weighted avg       0.52      0.57      0.54      2235

  Preparing green: 100%|██████████| 335/335 [00:00<00:00, 4133.02it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green
    Precision: 0.4542
    Recall:    0.3701
    F1:        0.4079
              precision    recall  f1-score   support

       SKILL       0.45      0.37      0.41       670

   micro avg       0.45      0.37      0.41       670
   macro avg       0.45      0.37      0.41       670
weighted avg       0.45      0.37      0.41       670

  Preparing gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 7739.17it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm
    Precision: 0.7842
    Recall:    0.8311
    F1:        0.8070
              precision    recall  f1-score   support

       SKILL       0.78      0.83      0.81       835

   micro avg       0.78      0.83      0.81       835
   macro avg       0.78      0.83      0.81       835
weighted avg       0.78      0.83      0.81       835


=======================================================
Model: jobspanbert
=======================================================

  Preparing sayfullina: 100%|██████████| 1851/1851 [00:00<00:00, 11097.47it/s]

Map:   0%|          | 0/1851 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  sayfullina
    Precision: 0.7964
    Recall:    0.8465
    F1:        0.8207
              precision    recall  f1-score   support

       SKILL       0.80      0.85      0.82      1857

   micro avg       0.80      0.85      0.82      1857
   macro avg       0.80      0.85      0.82      1857
weighted avg       0.80      0.85      0.82      1857

  Preparing skillspan: 100%|██████████| 3569/3569 [00:00<00:00, 10019.77it/s]

Map:   0%|          | 0/3569 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  skillspan
    Precision: 0.5135
    Recall:    0.5539
    F1:        0.5329
              precision    recall  f1-score   support

       SKILL       0.51      0.55      0.53      2235

   micro avg       0.51      0.55      0.53      2235
   macro avg       0.51      0.55      0.53      2235
weighted avg       0.51      0.55      0.53      2235

  Preparing green: 100%|██████████| 335/335 [00:00<00:00, 4852.02it/s]

Map:   0%|          | 0/335 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  green
    Precision: 0.4490
    Recall:    0.3746
    F1:        0.4085
              precision    recall  f1-score   support

       SKILL       0.45      0.37      0.41       670

   micro avg       0.45      0.37      0.41       670
   macro avg       0.45      0.37      0.41       670
weighted avg       0.45      0.37      0.41       670

  Preparing gnehm: 100%|██████████| 2557/2557 [00:00<00:00, 14553.67it/s]

Map:   0%|          | 0/2557 [00:00<?, ? examples/s]

/tmp/ipykernel_1528/132801876.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  evaluator = Trainer(

  gnehm
    Precision: 0.7712
    Recall:    0.7948
    F1:        0.7828
              precision    recall  f1-score   support

       SKILL       0.77      0.79      0.78       848

   micro avg       0.77      0.79      0.78       848
   macro avg       0.77      0.79      0.78       848
weighted avg       0.77      0.79      0.78       848



=== SUMMARY ===
      model    dataset  precision  recall     f1
  bert-base sayfullina     0.8007  0.8568 0.8278
  bert-base  skillspan     0.4894  0.5141 0.5014
  bert-base      green     0.4991  0.4030 0.4459
  bert-base      gnehm     0.8164  0.8359 0.8260
   spanbert sayfullina     0.7795  0.8223 0.8003
   spanbert  skillspan     0.4761  0.4770 0.4765
   spanbert      green     0.4566  0.3532 0.3983
   spanbert      gnehm     0.7816  0.8012 0.7913
    jobbert sayfullina     0.7836  0.8363 0.8091
    jobbert  skillspan     0.5194  0.5687 0.5429
    jobbert      green     0.4542  0.3701 0.4079
    jobbert      gnehm     0.7842  0.8311 0.8070
jobspanbert sayfullina     0.7964  0.8465 0.8207
jobspanbert  skillspan     0.5135  0.5539 0.5329
jobspanbert      green     0.4490  0.3746 0.4085
jobspanbert      gnehm     0.7712  0.7948 0.7828

Saved results_prf.csv
Saved predictions_tokens.csv  (409784 rows)

        model     dataset  example_id  token_id        token     gold     pred
0   bert-base  sayfullina           0         0           be        O        O
1   bert-base  sayfullina           0         1         look        O        O
2   bert-base  sayfullina           0         2          for        O        O
3   bert-base  sayfullina           0         3            a        O        O
4   bert-base  sayfullina           0         4    temporary        O        O
5   bert-base  sayfullina           0         5  opportunity        O        O
6   bert-base  sayfullina           0         6       within        O        O
7   bert-base  sayfullina           0         7            a        O        O
8   bert-base  sayfullina           0         8  progressive        O        O
9   bert-base  sayfullina           0         9          and        O        O
10  bert-base  sayfullina           0        10      dynamic  B-SKILL  B-SKILL
11  bert-base  sayfullina           0        11  environment        O        O
12  bert-base  sayfullina           0        12            ,        O        O
13  bert-base  sayfullina           0        13       please        O        O
14  bert-base  sayfullina           0        14      forward        O        O
15  bert-base  sayfullina           0        15         your        O        O
16  bert-base  sayfullina           0        16           cv        O        O
17  bert-base  sayfullina           0        17        today        O        O
18  bert-base  sayfullina           1         0    effective        O        O
19  bert-base  sayfullina           1         1       member        O        O